---
- hosts: workers
  become: yes
  tasks:
  - name: vim default
    apt:
      name: vim
      state: present

  - name: update[grade]
    apt:
      update_cache: yes
      upgrade: full
    register: updates

  - name: reboot
    ansible.builtin.reboot:
    when: updates.changed
